spring:
  data:
    redis:
      host: 172.16.2.10
      port: 6379
      password: c1$4T&9pW#z2Q@7vL
      database: 6
  datasource:
    hikari:
      maximum-pool-size: 100
      minimum-idle: 10
      idle-timeout: 300000
      auto-commit: true
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  messages:
    basename: i18n/commons,i18n/api,i18n/bug,i18n/case,i18n/plan,i18n/project,i18n/system
    default-locale: zh_CN
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          scheduler:
            instanceName: test-hub-quartz
            instanceId: AUTO #默认主机名和时间戳生成实例ID,可以是任何字符串，但对于所有调度程序来说，必须是唯一的 对应qrtz_scheduler_state INSTANCE_NAME字段
          jobStore:
            #            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore #持久化配置
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
          threadPool:
            threadCount: 10
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis-flex:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3306/meta-sphere?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      username: root
      password: 123456
    #      password: 3eCrAw8Ba6Tg
    ds-slave1:
      url: jdbc:mysql://172.16.2.10:3306/ruoyi-vue-pro?allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
      username: root
      password: 3eCrAw8Ba6Tg
    ds-slave2:
      url: jdbc:mysql://172.16.2.15:3306/nmfm_lt?allowPublicKeyRetrieval=true&allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true&nullCatalogMeansCurrent=true # MySQL Connector/J 8.X 连接的示例
      username: root
      password: Zkah@83539595S
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jwt:
  secret: K4lgrcqOP576NhrtYJhuQD8DdMYfZtb58hWdJaTjPbk=
  access-token-validity: 43200000 #2h
  refresh-token-validity: 604800000 # 7d
influx:
  url: http://172.16.2.10:8086
  token: CgfdhyPnh-GIrYtLV37zLffC4mvP620xRXA6mu2BRThTrnWwNJp1b6Pl5dpGnykgYhg5EoI0WptScdKq7YKZ2g==
  org: admin
  bucket: analyse
jmeter:
#  home: /opt/apache-jmeter-5.6.2   # 你的 JMeter 安装路径
  home: F:\apache-jmeter-5.6.2   # 你的 JMeter 安装路径
  results.dir: ./results
  reports.dir: ./reports
logging:
  level:
    web: info # Web 模块日志级别
    org.springframework.web: info  # Spring Web 框架日志
    org.springframework.boot.web.servlet: info  # Servlet 容器日志
    org.springframework.security: info